Pepcus/yjsgUI

package.json, src/components/AdvanceFilter.jsx, src/components/AdvanceSearch.js, src/components/DataGrid.jsx
Added advance search feature in YJSG.
=> Added advance search feature in YJSG.

package.json, src/components/AdvanceSearch.js, src/components/DataGrid.jsx, src/dataGrid.css, src/tableGrid.css
Applied CSS for Advance-search-filter.
=> advance filter styling modified

src/actions/studentRegistrationActions.js, src/components/AdminPanel.jsx, src/components/AdvanceSearch.js, src/components/ColumnConfig.jsx, src/components/DataGrid.jsx, src/components/StudentRegistrationCorrectionForm.jsx, src/dataGrid.css, src/index.css, src/reducers/studentRegistrationReducer.js
Added select All, select null buttons for column options.
=> Added select All, select null buttons for column options.

src/actions/studentRegistrationActions.js, src/components/AdminPanel.jsx, src/components/ColumnConfig.jsx, src/components/DataGrid.jsx, src/components/SplashPage.jsx, src/components/SplashPagePrePopulated.jsx, src/components/StudentRegistrationForm.jsx, src/components/coreComponents/Routes.jsx, src/reducers/studentRegistrationReducer.js, src/sagas/rootSaga.js
Change url of student information page and SplashPagePrePopulated to Home.
=> Solved bug of student update by admin.

src/components/DataGrid.jsx, src/components/IdCardWrapper.js, src/dataGrid.css, src/tableGrid.css
I applied column option validation styling when no option applied.
=> empty column message validation applied

src/actions/studentRegistrationActions.js, src/components/DataGrid.jsx, src/components/GridData.jsx, src/components/UpdateIdCardStatusSelectedStudents.jsx
Added JS DOC.
Done few refactoring.
=> Addend edit button column to second position in student grid.

package.json, src/components/AdvanceSearch.jsx, src/components/DataGrid.jsx, src/components/StudentRegistrationCorrectionFormURL.jsx, src/dataGrid.css
Solved bug of student correction form through URL.
changed version of simple-react-data-grid.
Added clear search functionality in advance search.
=> Solved bug of checkbox in student gird.

package.json, src/components/GridData.jsx, src/components/StudentCredentialPage.jsx, src/components/StudentInformationGrid.jsx, src/dataGrid.css
#2  Added feature of loader for select all.
#3 Added popup for all export.
=> Change version of simple-react-data-grid from 2.3.0 to 2.4.0.

src/components/common/Popup.jsx, src/components/routeComponents/memberInformationGrid/FileDownloadMessagePopup.jsx, src/components/routeComponents/memberInformationGrid/SelectedMembersActionWrapper.jsx, src/components/routeComponents/memberRegistrationForm/SuccessMessagePopup.jsx, src/constants/theme.js
A generic pop-up with pepcus core library.
=> Generic popup with pepcus core library.

src/components/common/Header.jsx, src/components/routeComponents/memberInformationGrid/MemberInformationGrid.jsx, src/components/routeComponents/memberInformationGrid/advanceSearch/AdvanceSearch.jsx, src/config/appConfig.json, src/index.js
Generic header with Pepcus core.
=> Header with pepcus core.

src/components/common/Footer.jsx, src/components/common/Header.jsx, src/components/common/Popup.jsx, src/components/core/AppContainer.jsx, src/components/core/Routes.jsx, src/components/routeComponents/ParentsRegistrationForm.jsx, src/config/appConfig.json, src/constants/theme.js, src/constants/yjsg.js
Footer,  AppContainer, and Routes with pepcus core
=> Footer, AppContainer and Routes with pepcus core

src/components/common/fields/InputField.jsx, src/components/common/fields/SelectList.jsx, src/components/routeComponents/memberRegistrationForm/MemberRegistrationForm.jsx, src/config/tenant/YJSG-Bhopal/Registration.json, src/config/tenant/YJSG-Indore/Registration.json
Member registration page responsiveness.
=> Member registration page responsiveness.

src/components/common/fields/InputField.jsx, src/components/common/fields/SelectList.jsx, src/config/tenant/YJSG-Bhopal/ADMIN.json, src/config/tenant/YJSG-Bhopal/STUDENT.json, src/config/tenant/YJSG-Indore/STUDENT.json
=> Responsiveness.

src/components/routeComponents/memberCredentialPage/MemberCredentialPage.jsx, src/components/routeComponents/memberInformationGrid/MobileButtons.jsx, src/components/routeComponents/memberInformationGrid/advanceSearch/AdvanceSearch.jsx, src/components/routeComponents/memberInformationGrid/advanceSearch/advanceSearchShema.json, src/components/routeComponents/memberRegistrationForm/MemberRegistrationForm.jsx, src/components/routeComponents/parentsRegistrationForm/CloseBrowserPopup.jsx, src/components/routeComponents/parentsRegistrationForm/ParentsRegistrationForm.jsx, src/components/routeComponents/splashPage/AdminLoginForm.jsx, src/components/routeComponents/splashPage/SplashPage.jsx, src/config/tenant/YJSG-Bhopal/onlyEditOptIn.json
=> Solving few bugs.

src/assets/css/dataGrid.css, src/components/routeComponents/memberInformationGrid/SelectedMembersActionWrapper.jsx
Solved member information grid scroll bug and selected member information CSV export bug.
=> Solved grid scroll and export link bug.

.eslintrc.js, src/api/assetFilesAPI.js, src/api/formConfigAPI.js, src/api/memberRegisterAPI.js, src/components/routeComponents/files/Files.jsx, src/components/routeComponents/memberRegistrationCorrectionForm/MemberRegistrationCorrectionForm.jsx, src/components/routeComponents/memberRegistrationForm/MemberRegistrationForm.jsx, src/index.js, src/sagas/assetFilesSaga.js, src/sagas/rootSaga.js, webpack.config.js
=> Separate out sagas and APIs.

src/actions/allMembersDataActions.js, src/actions/appActions.js, src/actions/assetFilesActions.js, src/actions/loaderActions.js, src/actions/memberRegistrationActions.js, src/actions/parentsRegistrationAction.js, src/apis/memberRegisterAPI.js, src/components/common/Header.jsx, src/components/core/AppContainer.jsx, src/components/routeComponents/files/Files.jsx, src/components/routeComponents/memberCredentialPage/MemberCredentialPage.jsx, src/components/routeComponents/memberInformationGrid/MemberInformationGrid.jsx, src/components/routeComponents/memberInformationGrid/markOptInOrOptOutSelectedMember/MarkOptInOrOptOutSelectedMember.jsx, src/components/routeComponents/memberInformationGrid/markSelectedMembersAttendance/MarkSelectedMembersAttendance.jsx, src/components/routeComponents/memberInformationGrid/updateIdCardStatusMembersModal/UpdateIdCardStatusMembersModal.jsx, src/components/routeComponents/memberInformationGrid/uploadMembersAttendanceFile/UploadMembersAttendanceFile.jsx, src/components/routeComponents/memberInformationGrid/uploadMembersOptInFile/UploadMembersOptInFile.jsx, src/components/routeComponents/memberPage/MemberPage.jsx, src/components/routeComponents/memberRegistrationCorrectionForm/MemberRegistrationCorrectionForm.jsx, src/components/routeComponents/memberRegistrationForm/MemberRegistrationForm.jsx, src/components/routeComponents/parentsRegistrationForm/ParentsRegistrationForm.jsx, src/components/routeComponents/splashPage/SplashPage.jsx, src/reducers/allMembersDataReducer.js, src/reducers/appReducer.js, src/reducers/parentsRegistrationReducer.js, src/reducers/rootReducer.js, src/sagas/rootSaga.js
Refactor actions and have separate actions for each root reducer.
=> Refactor actions and have separate actions for each root reducer.

src/components/common/Header.jsx, src/components/common/fields/InputField.jsx, src/components/routeComponents/files/Files.jsx, src/components/routeComponents/memberInformationGrid/MemberInformationGrid.jsx, src/components/routeComponents/memberInformationGrid/SelectedMembersActionWrapper.jsx, src/components/routeComponents/memberInformationGrid/advanceSearch/AdvanceSearch.jsx, src/components/routeComponents/memberInformationGrid/membersIdCard/MembersIdCard.jsx, src/components/routeComponents/memberRegistrationCorrectionForm/FormUpdateSuccessMessage.jsx, src/components/routeComponents/memberRegistrationCorrectionForm/MemberRegistrationCorrectionForm.jsx, src/components/routeComponents/memberRegistrationForm/MemberRegistrationForm.jsx, src/components/routeComponents/parentsRegistrationForm/ParentsRegistrationForm.jsx
Solved es-linting warning and errors.
=> Fix few linting errors.

src/apis/http.js, src/components/core/Routes.jsx, src/components/routeComponents/memberInformationGrid/SelectedMembersActionWrapper.jsx, src/constants/theme.js
=> Input field focus style.

src/apis/file/file.js, src/apis/member/member.js, src/sagas/rootSaga.js
=> Refactored APIs

src/actions/app.js, src/actions/assetFilesActions.js, src/components/core/AppContainer.jsx, src/components/core/EventManagement.jsx, src/reducers/app.js, src/reducers/assetFilesReducer.js, src/reducers/rootReducer.js, src/sagas/assetFilesSaga.js, src/sagas/core.js, src/sagas/index.js
Combined all core APIs sagas call in single bootstrap API sagas.
=> Core APIs call combine in single bootstrap AIP sagas

src/components/routeComponents/memberCredentialPage/MemberCredentialPage.jsx, src/components/routeComponents/memberPage/MemberPage.jsx, src/components/routeComponents/memberRegistrationCorrectionForm/MemberRegistrationCorrectionForm.jsx, src/components/routeComponents/memberRegistrationForm/MemberRegistrationForm.jsx, src/components/routeComponents/splashPage/SplashPage.jsx, src/config/tenant/default/ADMIN.json, src/config/tenant/default/Registration.json, src/config/tenant/default/STUDENT.json, src/config/tenant/default/onlyEditOptIn.json, src/constants/yjsg.js, src/utils/form/formDataUtils.js, ui_config/app.json
Default tenant configuration and code refactored as per default tenant.
=> Default tenant configuration and code refactored.

src/components/common/Footer.jsx, src/components/common/Header.jsx, src/components/core/Routes/Routes.jsx, src/components/routeComponents/memberInformationGrid/DesktopButtons.jsx
Footer and header configuration form tenant app configuration.
=> Footer and header configuration form tenant app configuration.

package.json, src/actions/api.js, src/apis/core/bootstrap.js, src/apis/member/member.js, src/config/tenant/default/api/api.json, src/reducers/api.js, src/reducers/rootReducer.js, src/sagas/core/bootstrap.js, src/sagas/member.js, src/store/store.js, src/utils/apis/formatters/formatter.js, src/utils/apis/formatters/index.js, src/utils/common/string.js
For https://github.com/Pepcus/yjsgUI/issues/184
=> Added support for configurable API endpoints in the application

src/apis/apis.js, src/apis/member/member.js, src/sagas/member.js
APIs call function refactored.
=> APIs call function refactored.

src/apis/apis.js, src/components/routeComponents/files/Files.jsx, src/config/tenant/default/api/api.json, src/sagas/file.js, src/utils/apis/formatters/YJSG-Bhopal/headerFormatters.js, src/utils/apis/formatters/YJSG-Bhopal/index.js, src/utils/apis/formatters/YJSG-Indore/headerFormatters.js, src/utils/apis/formatters/YJSG-Indore/index.js, src/utils/apis/formatters/default/headerFormatters.js, src/utils/apis/formatters/default/index.js, src/utils/routes/files/fileUtils.js
Make all API endpoints and response formatter driven from tenant JSON.
=> Make all API endpoints and response formatter driven from tenant JSON

package.json, src/components/common/fields/ErrorList.jsx, src/components/common/fields/FormGroup.jsx, src/components/common/fields/FormGroupTitle.jsx, src/components/common/fields/InputField.jsx, src/components/common/fields/SelectList.jsx, src/components/common/fields/UploadFileField.jsx, src/components/common/fields/index.js, src/components/routeComponents/memberRegistrationForm/MemberRegistrationForm.jsx, src/components/routeComponents/splashPage/LoginForm.jsx, src/config/tenant/default/constants/text.json, src/config/tenant/default/routes/memberRegistration.json, src/config/tenant/default/routes/memberRegistrationCorrection.json
Added field template support for form and change the position of registration button of the admin page. Converted default tenant Hindi text into English text.
=> Added field template support.

src/components/routeComponents/memberRegistrationCorrectionForm/MemberRegistrationCorrectionForm.jsx, src/components/routeComponents/memberRegistrationForm/MemberRegistrationForm.jsx
Solved bug of mandatory field error.
=> Solved bug of mandatory field error.

src/components/routeComponents/memberRegistrationCorrectionForm/MemberRegistrationCorrectionForm.jsx, src/components/routeComponents/memberRegistrationForm/MemberRegistrationForm.jsx, src/components/routeComponents/parentsRegistrationForm/ParentsRegistrationForm.jsx, src/config/tenant/YJSG-Bhopal/routes/memberRegistration.json, src/config/tenant/YJSG-Bhopal/routes/memberRegistrationCorrection.json, src/config/tenant/YJSG-Bhopal/routes/parentsRegistrationForm.json, src/config/tenant/YJSG-Indore/routes/memberRegistration.json, src/config/tenant/YJSG-Indore/routes/memberRegistrationCorrection.json, src/config/tenant/YJSG-Indore/routes/parentsRegistrationForm.json, src/config/tenant/default/routes/memberRegistration.json, src/config/tenant/default/routes/memberRegistrationCorrection.json, src/config/tenant/default/routes/parentsRegistrationForm.json, src/utils/form/formDataUtils.js, src/utils/form/formUtils.js
Modified form fields custom validation.
=> Form fields custom validation.

src/components/common/fields/ErrorList.jsx, src/components/routeComponents/memberInformationGrid/CSVExportButton.jsx, src/components/routeComponents/memberInformationGrid/DesktopButtons.jsx, src/components/routeComponents/memberInformationGrid/IdCardPrintButton.jsx, src/components/routeComponents/memberInformationGrid/MemberInformationGrid.jsx, src/components/routeComponents/memberInformationGrid/SelectedMembersActionWrapper.jsx, src/components/routeComponents/memberInformationGrid/advanceSearch/AdvanceSearch.jsx, src/components/routeComponents/memberInformationGrid/markOptInOrOptOutSelectedMember/MarkOptInOrOptOutSelectedMember.jsx, src/components/routeComponents/memberInformationGrid/markSelectedMembersAttendance/MarkSelectedMembersAttendance.jsx, src/components/routeComponents/memberInformationGrid/membersIdCard/MembersIdCard.jsx, src/components/routeComponents/memberInformationGrid/updateIdCardStatusMembersModal/UpdateIdCardStatusMembersModal.jsx, src/components/routeComponents/memberInformationGrid/uploadMembersAttendanceFile/UploadMembersAttendanceFile.jsx, src/components/routeComponents/memberInformationGrid/uploadMembersOptInFile/UploadMembersOptInFile.jsx, src/config/tenant/YJSG-Bhopal/constants/text.json, src/config/tenant/YJSG-Indore/constants/text.json, src/config/tenant/default/constants/text.json
Solved all PR comments, modified default tenant constants and used the access control component.
=> Solved all PR comments and use access control component.
